[tool.poetry]
name = "dio - banco"
version = "0.1.0"
description = ""
authors = ["Alisson Noli"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "*"
flask-sqlalchemy = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
